version: '3.9'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_app_python
    depends_on:
      - db
    restart: always
    ports:
      - "8050:8050"


