FROM ngrok/ngrok:latest


RUN apt-get update && apt-get install -y jq

RUN ngrok config add-authtoken 2TiRWPzg9P0JQfnxBYcrZsLJ2Rs_61SGxkBEabwZU3KYo2mNE

COPY ngrok.yml /ngrok.yml

COPY get_ngrok_url.sh /get_ngrok_url.sh
RUN chmod +x /get_ngrok_url.sh

ENTRYPOINT [ "ngrok", "start", "--all" ]
